### ISSUE TITLE
Use `PermissionDenied` instead of `HttpResponseForbidden`

### ISSUE THREAD

**Issue by mblayman** [mblayman/django-denied#6]
By using `HttpResponseForbidden` in the middleware, there is no chance for the `permission_denied` handler to return an appropriate custom response. The current result is that the 403 response is a totally blank page.

https://docs.djangoproject.com/en/4.1/ref/views/#the-403-http-forbidden-view

I need to figure out if `PermissionDenied` can be raised in the middleware stack. If so, the middleware should probably raise that instead of returning the empty 403 response directly.

FYI, @Tobi-De

**Comment by mblayman** [comment]
Released with 1.2

**Comment by Tobi-De** [comment]
Nice, good job 😀
