### ISSUE TITLE
Can't access media files

### ISSUE THREAD

**Issue by pedromsilva99** [mblayman/django-denied#60]
I am developing an app in the local environment.
When I try to access local images on the MEDIA_URL, I am getting a PermissionDenied exception coming from the Denied Middleware.
Django is finding the image, but can't display it because of that exception.
I've been checking the documentation and I could not find anything about media files.
How can I create an authorizer for media files?

**Comment by mblayman** [comment]
Thank you for the report.

Unfortunately, I don't have a quick answer for you as you've hit a case that I have not accounted for. I originally built django-denied or a project that I already had up on the web. One of the things that is uses is the S3 storage option from django-storages. Thus, all the media files that I tested against had AWS URLs.

In this case, it sound like you're using local files and hitting something that may use `MEDIA_URL`. The middleware does not currently consider that as I didn't think that media URLs went through the middleware stack. The middleware probably needs something like:

```python
if settings.MEDIA_URL and request.path.startswith(settings.MEDIA_URL):
    return None
```

I may be able to add that soon.
